language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - coverage run -m pytest test.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - coverage xml
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
